name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      - name: Connect to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/key.pem \
          ec2-user@15.207.248.91 \
          "hostname"
    